language: node_js
node_js: stable
sudo: required
before_script: npm install -g polymer-cli @advanced-rest-client/wct-istanbub
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sauce_connect: true
script:
- npm test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test:sl; fi
env:
  global:
    - secure: >-
        dvKWn7HawVroKLUZFTwkYSsaQqyqZLgL4eRd2SIiKoARqC8kvaMWYQjdEIr/spWpxtLffF3cW0HYGlbuN0qbpTI64Z/00oogLBog/NfOe6rpPkUoXeHJr1VRpw+S73UzWWoCADHxmWswo3++EeaAVbMeoV8VkHnlaJiKBQpXj+B0euJiTaFYR6Tn7R3dQciRs8HNq2tDt2mTZ1KuH5x4HRVBItmg8G5zcGVHfpOmZ1F2nvofTjech1AYydF6KTN6KQ3QajQ27/PcD7OPHUGzwVPvXQgrf1t5W5/zXwkSakRxhV3WfS1iUipj2bDN5yG8rJTK4rEkbL8g8hr7L7H9RgD4P7wrALepWQK0NlXOBqzTQVN/EgNL0H2iWSF7nKQt6Nck9qgUUNZZsK+nvMzqfF1nLYqmYO1A2UToYRjkR8pGFzFkn2XxYywGJtJHYuu8HGqGjYXhe1e+AG55q2nJoh1Qh+kxKi+rH6kdRMW9Bq23+g8a9ghcQ1JTsdhchsDKJOZiYbiSZKAnGMSkwIlUBKGiqMxsQkJRDyByH571t0cdtN9R9u6V5a4ULlEOBlKuCUJLlNAK69V4OxguF+EVuHxK0O38zl8TCbvIVjCI5T51nwB/Cw9NkFdclPO9xxq8VtFC3Ie8GQJ8SmbNKmdopefhYYTMoCu5alyhHQ9nuLk=
    - secure: >-
        F9sIatrCj4F3NsPqrtRiR+10h4bVlccwTwi/c4bXs/zLnjDtjidIzFj69TYRAyLn79rMNwGXCX8g2sie7hswfAEHcxlBHWwDPmDUcLUJ3gidWFWpbZjBA7UlII8UU+mEc2GLfUgzFYyTDfH5HvXnAOVpWhzOTV4690TZjJEfqgzCBy9Ng+HKepVVpKS/0ypuaYNGnXmf7TS+qy4U8/HFiwpkXmwy34hdLXDJChee23bcRMIGJbHa1lLJeACNQ5HFayOzpkJqRO23Mu7LJhi/pg9pXPDuNPJW4AUTKEHpnlNol5YEugE2D+1zPk0rLqMqh46fLbLuV632/36sLDzLj+RQ76waowB7TCU5zUQGmePQqgbg43VP7kKsuaLaLpUB0Kn0NJ8bmalBe31handktfLcinZkVLKQSAOAh3H/clKjSn1F2626/hZ/maBXfv9MiyK+7K7ha1QHJEL1T+scAVioAAVQwtB0QZxVVEZa9YHrGStG+Dk+2+2uC9aMdtdRzFYRCsEOV/grurQr1iC+7+RtsQedTLyxCpnAv60n22WfD8cfJq4iCPWe5GosXg0adBJNTcJvlhjQvxGd91f5bohDsY5B3YRjERX9yF5HgBRp17baFwX45qBRjq5+grJymAM8oiljtr01CoV3dyluJg4FrbwOf5dCWDtKHa3s8Sg=
